#define yy_create_buffer fractal_yy_create_buffer
#define yy_delete_buffer fractal_yy_delete_buffer
#define yy_scan_buffer fractal_yy_scan_buffer
#define yy_scan_string fractal_yy_scan_string
#define yy_scan_bytes fractal_yy_scan_bytes
#define yy_flex_debug fractal_yy_flex_debug
#define yy_init_buffer fractal_yy_init_buffer
#define yy_flush_buffer fractal_yy_flush_buffer
#define yy_load_buffer_state fractal_yy_load_buffer_state
#define yy_switch_to_buffer fractal_yy_switch_to_buffer
#define yyin fractal_yyin
#define yyleng fractal_yyleng
#define yylex fractal_yylex
#define yyout fractal_yyout
#define yyrestart fractal_yyrestart
#define yytext fractal_yytext
#define yywrap fractal_yywrap

#line 20 "fractal.lex.c"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <unistd.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 79
#define YY_END_OF_BUFFER 80
static yyconst short int yy_accept[309] =
    {   0,
        0,    0,    0,    0,    0,    0,   80,   73,   68,   69,
       73,   73,   72,   73,   73,   73,   73,   25,   73,    1,
        1,   58,   20,   59,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       73,   75,   74,   75,   78,   77,   62,    0,   67,   65,
       23,   56,   21,   57,   22,    2,   70,   71,   24,    2,
        1,    0,    0,   60,   63,    5,   61,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   13,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   64,   76,    2,    0,    2,    1,

       66,   66,   66,   66,   66,   66,   30,   66,   66,   66,
       14,   66,   66,   66,   66,   35,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   32,
       66,   66,   66,   34,   66,   66,   66,   66,   66,    1,
       66,   54,   66,   66,   66,   66,   66,   66,   12,   11,
       66,   66,   66,   66,   29,   66,   66,   66,   66,   40,
       66,   66,   66,   66,   66,   66,   66,   49,   66,   66,
       66,   66,   66,   28,   66,   66,   66,   66,   66,   38,
       66,    1,   18,   66,   66,   66,   66,   66,   66,   66,
       39,   66,   66,   66,   66,   66,   66,   66,   66,   66,

       66,   15,   48,   66,   66,   66,   47,   66,   66,   66,
       50,   66,   66,   66,   66,   66,   66,    7,    8,   66,
       66,   66,   10,   66,   66,   66,   66,   66,   51,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   44,   43,
       66,   66,   26,   66,   66,   53,   66,    9,   66,   55,
       30,    6,    3,   66,   66,   66,   66,    4,   31,   33,
       16,   66,   46,   66,   45,   32,   66,   66,   66,   19,
       27,   66,   66,   66,   66,   66,   41,   66,   66,   66,
       66,   29,   35,   17,   66,   66,   42,   36,   66,   66,
       66,   66,   66,   66,   66,   31,   33,   66,   66,   66,

       66,   66,   66,   37,   66,   66,   52,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    1,    7,    1,    1,
        1,    8,    9,    1,   10,   11,   12,   13,   14,   14,
       14,   14,   14,   14,   14,   14,   14,    1,    1,   15,
       16,   17,    1,    1,   18,   18,   18,   18,   19,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   20,   18,   18,
        1,    1,    1,    1,   21,    1,   22,   23,   24,   25,

       26,   27,   28,   29,   30,   18,   31,   32,   33,   34,
       35,   36,   37,   38,   39,   40,   41,   42,   43,   44,
       45,   18,    1,   46,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[47] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    2,    2,    1,    1,    1,    2,    2,    2,
        3,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    1
    } ;

static yyconst short int yy_base[314] =
    {   0,
        0,    0,   44,   45,  364,  363,  365,  368,  368,  368,
      348,  358,  368,  355,  345,   40,   41,   41,   50,   56,
       60,  344,   43,  343,    0,  320,   28,  331,  324,   42,
      317,   51,  332,  312,  320,  313,   66,   55,   57,  321,
      303,  368,  368,  336,  368,  368,  368,  342,  368,  368,
      368,  368,  368,  368,  368,   88,  368,  368,  368,   90,
       99,  110,    0,  368,  368,  368,  368,    0,  320,  306,
       57,   78,   69,  312,  305,  320,  319,    0,  318,  300,
       93,  306,  312,  306,  108,  310,   75,  294,  296,  299,
      301,  286,  288,  298,  368,  368,  114,  122,  124,   42,

      305,  300,  290,  288,  283,  109,  284,  294,  294,  280,
      285,  293,  291,  287,  284,  279,  105,  280,  290,  276,
      275,  115,  276,  272,  268,  270,  278,  267,  267,  271,
      268,  273,  277,    0,  276,  256,  255,  268,  261,  141,
      261,    0,  253,  258,  259,  247,  253,  260,    0,  255,
      258,  242,  242,  251,  250,  254,  248,  253,  246,    0,
      123,  235,  249,  235,  237,  239,  230,    0,  237,  244,
      232,  228,  243,    0,  242,  239,  227,  237,  239,    0,
      233,  143,    0,  219,  231,  222,  223,  228,  227,  225,
        0,  219,  228,  223,  214,  221,  206,  210,  210,  217,

      220,  209,    0,  216,  200,  208,    0,  192,  196,  203,
        0,  200,  193,  197,  204,  201,  199,    0,    0,  184,
      186,  186,    0,  186,  202,  191,  188,  199,    0,  179,
      187,  190,  189,  191,  181,  182,  174,  176,    0,    0,
      166,  171,    0,  177,  187,    0,  173,    0,  180,    0,
        0,    0,    0,  165,  166,  178,  167,    0,  163,  170,
        0,  173,    0,  159,    0,    0,  162,  157,  155,    0,
        0,  149,  167,  154,  165,  168,    0,  163,  150,  150,
      160,    0,    0,    0,  159,  150,    0,  162,  141,  143,
      129,  127,  136,  142,  124,    0,    0,  120,  120,  123,

       80,   91,   91,    0,   54,   32,    0,  368,  169,  172,
      175,  177,   63
    } ;

static yyconst short int yy_def[314] =
    {   0,
      308,    1,  309,  309,  310,  310,  308,  308,  308,  308,
      308,  311,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      308,  308,  308,  308,  308,  308,  308,  311,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  313,  308,  308,  308,  308,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  308,  308,  308,  308,  308,  313,

      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  313,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  313,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,

      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,

      312,  312,  312,  312,  312,  312,  312,    0,  308,  308,
      308,  308,  308
    } ;

static yyconst short int yy_nxt[415] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   24,   25,   25,   25,
       25,   25,   26,   27,   28,   29,   30,   31,   25,   32,
       25,   25,   33,   34,   35,   36,   25,   37,   38,   39,
       25,   25,   40,   25,   25,   41,   43,   43,   52,   70,
       54,   44,   44,   56,   56,   53,   55,   57,   65,   66,
      140,   58,   71,   74,  100,   59,   60,  140,   61,   61,
       60,  307,   61,   61,   62,   63,   75,   78,   62,   76,
       88,   62,   92,   79,   80,   62,   85,   86,  103,  104,
      105,   87,  134,   89,   93,   90,  131,   91,  108,   63,

       56,   56,   97,   97,  106,  107,   62,  109,   62,   60,
      132,   61,   61,   62,  306,   62,  305,   62,   98,   98,
      116,  304,   99,   99,   62,  158,   97,   97,  117,  121,
      146,  122,   62,  123,   99,   99,   99,   99,  147,   62,
      159,  124,  125,  126,  164,  127,  128,  200,  303,   98,
       98,  129,  165,  182,  182,  182,  182,  302,  301,  140,
      201,  140,  300,  299,  298,  297,  140,  296,  140,   42,
       42,   42,   45,   45,   45,   48,   48,   48,   68,   68,
      295,  294,  293,  292,  291,  290,  289,  288,  287,  286,
      285,  284,  283,  282,  281,  280,  279,  278,  277,  276,

      275,  274,  273,  272,  271,  270,  269,  268,  267,  266,
      265,  264,  263,  262,  261,  260,  259,  258,  257,  256,
      255,  254,  253,  252,  251,  250,  249,  248,  247,  246,
      245,  244,  243,  242,  241,  240,  239,  238,  237,  236,
      235,  234,  233,  232,  231,  230,  229,  228,  227,  226,
      225,  149,  224,  223,  222,  221,  220,  219,  218,  217,
      216,  215,  214,  213,  212,  211,  210,  209,  208,  207,
      206,  205,  204,  203,  202,  199,  198,  197,  196,  195,
      194,  193,  192,  191,  190,  189,  188,  187,  186,  185,
      184,  183,  181,  180,  179,  178,  177,  176,  175,  174,

      173,  172,  171,  170,  169,  168,  167,  166,  163,  162,
      161,  160,  157,  156,  155,  154,  153,  152,  151,  150,
      149,  148,  145,  144,  143,  142,  141,  139,  138,  137,
      136,  135,  134,  133,  130,  120,  119,  118,  115,  114,
      113,  112,  111,  110,  102,  101,   49,   96,   95,   94,
       84,   83,   82,   81,   77,   73,   72,   69,   67,   64,
       51,   50,   49,   47,  308,   46,   46,    7,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,

      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308
    } ;

static yyconst short int yy_chk[415] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    4,   16,   27,
       17,    3,    4,   18,   18,   16,   17,   19,   23,   23,
      100,   19,   27,   30,  313,   19,   20,  100,   20,   20,
       21,  306,   21,   21,   20,   20,   30,   32,   21,   30,
       38,   20,   39,   32,   32,   21,   37,   37,   71,   71,
       71,   37,  305,   38,   39,   38,   87,   38,   73,   20,

       56,   56,   60,   60,   72,   72,   56,   73,   60,   61,
       87,   61,   61,   56,  303,   60,  302,   61,   62,   62,
       81,  301,   62,   62,   61,  117,   97,   97,   81,   85,
      106,   85,   97,   85,   98,   98,   99,   99,  106,   97,
      117,   85,   85,   85,  122,   85,   85,  161,  300,  140,
      140,   85,  122,  140,  140,  182,  182,  299,  298,  140,
      161,  182,  295,  294,  293,  292,  140,  291,  182,  309,
      309,  309,  310,  310,  310,  311,  311,  311,  312,  312,
      290,  289,  288,  286,  285,  281,  280,  279,  278,  276,
      275,  274,  273,  272,  269,  268,  267,  264,  262,  260,

      259,  257,  256,  255,  254,  249,  247,  245,  244,  242,
      241,  238,  237,  236,  235,  234,  233,  232,  231,  230,
      228,  227,  226,  225,  224,  222,  221,  220,  217,  216,
      215,  214,  213,  212,  210,  209,  208,  206,  205,  204,
      202,  201,  200,  199,  198,  197,  196,  195,  194,  193,
      192,  190,  189,  188,  187,  186,  185,  184,  181,  179,
      178,  177,  176,  175,  173,  172,  171,  170,  169,  167,
      166,  165,  164,  163,  162,  159,  158,  157,  156,  155,
      154,  153,  152,  151,  150,  148,  147,  146,  145,  144,
      143,  141,  139,  138,  137,  136,  135,  133,  132,  131,

      130,  129,  128,  127,  126,  125,  124,  123,  121,  120,
      119,  118,  116,  115,  114,  113,  112,  111,  110,  109,
      108,  107,  105,  104,  103,  102,  101,   94,   93,   92,
       91,   90,   89,   88,   86,   84,   83,   82,   80,   79,
       77,   76,   75,   74,   70,   69,   48,   44,   41,   40,
       36,   35,   34,   33,   31,   29,   28,   26,   24,   22,
       15,   14,   12,   11,    7,    6,    5,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,

      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "fractal.lex"
#define INITIAL 0
#line 2 "fractal.lex"

// For prototype of "strdup"
#include <string.h>

#include "fractal.yacc.h"
#include "FractalLexer.h"
#include "dmemory.h"

/*****************************************************************************
 * Definitions for class "FractalLexer"
 *****************************************************************************/

FractalLexer::FractalLexer()
   : mLineNumber(1), mText(0), mTextIndex(0), mTextLength(0),
     mFileOffset(0), mLineOffset(0)
{}

FractalLexer *FractalLexer::getInstance()
{
   static FractalLexer theInstance;
   return(&theInstance);
}

int FractalLexer::parseInteger(char *theText)
{
   int base = 10;

   // Is 'theText' a hex value?  If so we'll treat it as such ...

   if(strncmp(theText, "0x", 2) == 0 ||
      strncmp(theText, "0X", 2) == 0)
   {
      base = 16;
   }

   return(strtol(theText, 0, base));
}

void FractalLexer::begin(const char *text)
{
   YY_NEW_FILE;

   mLineNumber = 1;
   mTextLength = strlen(text);
   mTextIndex  = 0;
   mFileOffset = 0;
   mLineOffset = 0;

   DNEW(mText, char[mTextLength]);

   memcpy(mText, text, mTextLength);
}

void FractalLexer::end()
{
   DADELETE(mText);
}

int FractalLexer::getLineNumber()
{
   return(mLineNumber);
}

void FractalLexer::nextLine()
{
   ++mLineNumber;
   mLineOffset = 0;
}

int FractalLexer::getText(char *dest, int maxSize)
{
   int bytesRemaining = mTextLength - mTextIndex;
   int count          = bytesRemaining > maxSize ? maxSize : bytesRemaining;

   memcpy(dest, mText, count);

   mTextIndex += count;

   return(count);
}

int FractalLexer::getFileOffset()
{
   return(mFileOffset);
}

int FractalLexer::getLineOffset()
{
   return(mLineOffset);
}

void FractalLexer::getCurrentLine(char *line)
{
   // Grab the current line until we reach a \n or MAX_LINE_LENGTH
   // characters, whichever is smaller

   int offset = getFileOffset() - getLineOffset();
   int i      = 0;

   for(i = 0; offset + i < mTextLength && i < MAX_LINE_LENGTH; i ++)
   {
      if(mText[offset + i] == '\n')
         break;

      line[i] = mText[offset + i];
   }

   line[i] = '\0';
}

void FractalLexer::advance(char *theText)
{
   int nChars = strlen(theText);

   mFileOffset += nChars;
   mLineOffset += nChars;
}

/*****************************************************************************
 * Local function prototypes
 *****************************************************************************/

static int my_yyinput(char *buffer, int maxsize);

extern "C"
{
   int yylex(YYSTYPE *yylval);
}

#undef YY_INPUT

#define YY_INPUT(buffer, count, maxsize) (count = my_yyinput(buffer, maxsize))

#define YY_DECL int yylex(YYSTYPE *yylval)

// Define this symbol so that the generated
// source does not contain a reference to "isatty" (a unix-specific function)

#define YY_ALWAYS_INTERACTIVE (1)

/* -- Use flex's "exclusive start states" feature to avoid having to
prefix <INITIAL> to all tokens that should be recognized
while in the default state, note "%x" rather than "%s" -- */
#define STATE_MULTI_LINE_COMMENT 1

#define STATE_SINGLE_LINE_COMMENT 2

#line 725 "fractal.lex.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp = NULL, *yy_bp = NULL;
	register int yy_act;

#line 156 "fractal.lex"


   /* -- Token handling for the default state -- */

#line 881 "fractal.lex.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 309 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 368 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 160 "fractal.lex"
{
   yylval->ivalue = FractalLexer::parseInteger(yytext);
   FractalLexer::getInstance()->advance(yytext);
   return(INTEGER);
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 166 "fractal.lex"
{
   yylval->dvalue = atof(yytext);
   FractalLexer::getInstance()->advance(yytext);
   return(REAL);
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 172 "fractal.lex"
{
   FractalLexer::getInstance()->advance(yytext);
   return(FRACTAL);
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 177 "fractal.lex"
{
   FractalLexer::getInstance()->advance(yytext);
   return(MAPPING);
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 182 "fractal.lex"
{
   FractalLexer::getInstance()->advance(yytext);
   return(POINTTO);
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 187 "fractal.lex"
{
   FractalLexer::getInstance()->advance(yytext);
   return(FORMULA);
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 192 "fractal.lex"
{
   FractalLexer::getInstance()->advance(yytext);
   return(WHILE);
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 197 "fractal.lex"
{
   FractalLexer::getInstance()->advance(yytext);
   return(COLORS);
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 202 "fractal.lex"
{
   FractalLexer::getInstance()->advance(yytext);
   return(COMPLEX);
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 207 "fractal.lex"
{
   FractalLexer::getInstance()->advance(yytext);
   return(DEFINE);
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 212 "fractal.lex"
{
   FractalLexer::getInstance()->advance(yytext);
   return(ELSE);
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 217 "fractal.lex"
{
   FractalLexer::getInstance()->advance(yytext);
   return(ELSEIF);
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 222 "fractal.lex"
{
   FractalLexer::getInstance()->advance(yytext);
   return(IF);
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 227 "fractal.lex"
{
   FractalLexer::getInstance()->advance(yytext);
   return(FOR);
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 232 "fractal.lex"
{
   FractalLexer::getInstance()->advance(yytext);
   return(PRINT);
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 237 "fractal.lex"
{
   FractalLexer::getInstance()->advance(yytext);
   return(PRINTLN);
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 242 "fractal.lex"
{
   FractalLexer::getInstance()->advance(yytext);
   return(MAP_COLOR);
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 247 "fractal.lex"
{
   FractalLexer::getInstance()->advance(yytext);
   return(BREAK);
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 252 "fractal.lex"
{
   FractalLexer::getInstance()->advance(yytext);
   return(CONTINUE);
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 257 "fractal.lex"
{
   FractalLexer::getInstance()->advance(yytext);
   return(EQUALS);
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 262 "fractal.lex"
{
   FractalLexer::getInstance()->advance(yytext);
   return(PLUS_EQUALS);
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 267 "fractal.lex"
{
   FractalLexer::getInstance()->advance(yytext);
   return(MINUS_EQUALS);
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 272 "fractal.lex"
{
   FractalLexer::getInstance()->advance(yytext);
   return(TIMES_EQUALS);
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 277 "fractal.lex"
{
   FractalLexer::getInstance()->advance(yytext);
   return(DIVIDE_EQUALS);
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 282 "fractal.lex"
{
   FractalLexer::getInstance()->advance(yytext);
   return(DOT);
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 287 "fractal.lex"
{
   FractalLexer::getInstance()->advance(yytext);
   return(REPEAT);
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 292 "fractal.lex"
{
   FractalLexer::getInstance()->advance(yytext);
   return(GRADIENT);
}
	YY_BREAK
/***********************************************************************
    * Note that for the majority of the complex attributes
    * (real, imaginary, etc.) there is a long and short form of the
    * attribute.  These long and short forms *must* be kept in sync with
    * the strings listed in AttributeDoubleNode::lookup().  It would have
    * been nice to not have had to make the attributes into tokens but
    * going that route ended up causing ambiguity problems with the
    * grammar
    ***********************************************************************/
case 28:
YY_RULE_SETUP
#line 307 "fractal.lex"
{
   yylval->complexAttribute = strdup(yytext);
   FractalLexer::getInstance()->advance(yytext);
   return(ATTRIBUTE_REAL);
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 313 "fractal.lex"
{
   yylval->complexAttribute = strdup(yytext);
   FractalLexer::getInstance()->advance(yytext);
   return(ATTRIBUTE_IMAGINARY);
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 319 "fractal.lex"
{
   yylval->complexAttribute = strdup(yytext);
   FractalLexer::getInstance()->advance(yytext);
   return(ATTRIBUTE_DEGREES);
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 325 "fractal.lex"
{
   yylval->complexAttribute = strdup(yytext);
   FractalLexer::getInstance()->advance(yytext);
   return(ATTRIBUTE_OLD_DEGREES);
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 331 "fractal.lex"
{
   yylval->complexAttribute = strdup(yytext);
   FractalLexer::getInstance()->advance(yytext);
   return(ATTRIBUTE_RADIANS);
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 337 "fractal.lex"
{
   yylval->complexAttribute = strdup(yytext);
   FractalLexer::getInstance()->advance(yytext);
   return(ATTRIBUTE_OLD_RADIANS);
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 343 "fractal.lex"
{
   yylval->complexAttribute = strdup(yytext);
   FractalLexer::getInstance()->advance(yytext);
   return(ATTRIBUTE_SUM_OF_SQUARES);
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 349 "fractal.lex"
{
   yylval->complexAttribute = strdup(yytext);
   FractalLexer::getInstance()->advance(yytext);
   return(ATTRIBUTE_MAGNITUDE);
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 355 "fractal.lex"
{
   FractalLexer::getInstance()->advance(yytext);
   return(SET_COLOR);
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 360 "fractal.lex"
{
   FractalLexer::getInstance()->advance(yytext);
   return(SET_COLOR_HSV);
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 365 "fractal.lex"
{
   FractalLexer::getInstance()->advance(yytext);
   return(TOKEN_TRUE);
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 370 "fractal.lex"
{
   FractalLexer::getInstance()->advance(yytext);
   return(TOKEN_FALSE);
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 375 "fractal.lex"
{
   FractalLexer::getInstance()->advance(yytext);
   return(TOKEN_NULL);
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 380 "fractal.lex"
{
   FractalLexer::getInstance()->advance(yytext);
   return(R_CIRCLE);
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 385 "fractal.lex"
{
   FractalLexer::getInstance()->advance(yytext);
   return(R_ELLIPSE);
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 390 "fractal.lex"
{
   FractalLexer::getInstance()->advance(yytext);
   return(R_RECT);
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 395 "fractal.lex"
{
   FractalLexer::getInstance()->advance(yytext);
   return(R_POLY);
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 400 "fractal.lex"
{
   FractalLexer::getInstance()->advance(yytext);
   return(R_SPOLY);
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 405 "fractal.lex"
{
   FractalLexer::getInstance()->advance(yytext);
   return(R_CROSS);
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 410 "fractal.lex"
{
   FractalLexer::getInstance()->advance(yytext);
   return(R_NOT);
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 415 "fractal.lex"
{
   FractalLexer::getInstance()->advance(yytext);
   return(R_AND);
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 420 "fractal.lex"
{
   FractalLexer::getInstance()->advance(yytext);
   return(R_OR);
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 425 "fractal.lex"
{
   FractalLexer::getInstance()->advance(yytext);
   return(R_XOR);
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 430 "fractal.lex"
{
   FractalLexer::getInstance()->advance(yytext);
   return(INSIDE);
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 435 "fractal.lex"
{
   FractalLexer::getInstance()->advance(yytext);
   return(TEXT_INTERSECT);
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 440 "fractal.lex"
{
   FractalLexer::getInstance()->advance(yytext);
   return(SWITCH);
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 445 "fractal.lex"
{
   FractalLexer::getInstance()->advance(yytext);
   return(CASE);
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 450 "fractal.lex"
{
   FractalLexer::getInstance()->advance(yytext);
   return(DEFAULT);
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 455 "fractal.lex"
{
   FractalLexer::getInstance()->advance(yytext);
   return(PLUS_PLUS);
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 460 "fractal.lex"
{
   FractalLexer::getInstance()->advance(yytext);
   return(MINUS_MINUS);
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 466 "fractal.lex"
{
   FractalLexer::getInstance()->advance(yytext);
   return(LT);
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 471 "fractal.lex"
{
   FractalLexer::getInstance()->advance(yytext);
   return(GT);
}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 476 "fractal.lex"
{
   FractalLexer::getInstance()->advance(yytext);
   return(LE);
}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 481 "fractal.lex"
{
   FractalLexer::getInstance()->advance(yytext);
   return(GE);
}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 486 "fractal.lex"
{
   FractalLexer::getInstance()->advance(yytext);
   return(NE);
}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 491 "fractal.lex"
{
   FractalLexer::getInstance()->advance(yytext);
   return(EQ);
}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 496 "fractal.lex"
{
   FractalLexer::getInstance()->advance(yytext);
   return(OR);
}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 501 "fractal.lex"
{
   FractalLexer::getInstance()->advance(yytext);
   return(AND);
}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 506 "fractal.lex"
{
   yylval->identifier = strdup(yytext);
   FractalLexer::getInstance()->advance(yytext);
   return(IDENTIFIER);
}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 512 "fractal.lex"
{

   // Strip the quotes from around 'literal'

   yylval->literal = strdup(yytext + 1);
   yylval->literal[strlen(yytext) - 2] = '\0';

   FractalLexer::getInstance()->advance(yytext);
   return(LITERAL);
}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 523 "fractal.lex"
{
   /* -- Ignore whitespace -- */
   FractalLexer::getInstance()->advance(yytext);
}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 528 "fractal.lex"
{
   FractalLexer::getInstance()->advance(yytext);
   FractalLexer::getInstance()->nextLine();
}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 533 "fractal.lex"
{
   FractalLexer::getInstance()->advance(yytext);
   BEGIN STATE_MULTI_LINE_COMMENT;
}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 538 "fractal.lex"
{
   FractalLexer::getInstance()->advance(yytext);
   BEGIN STATE_SINGLE_LINE_COMMENT;
}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 543 "fractal.lex"
{
   FractalLexer::getInstance()->advance(yytext);
   BEGIN STATE_SINGLE_LINE_COMMENT;
}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 548 "fractal.lex"
{
   FractalLexer::getInstance()->advance(yytext);
   return(*yytext);
}
	YY_BREAK
/* -- Token handling for STATE_MULTI_LINE_COMMENT  -- */
case 74:
YY_RULE_SETUP
#line 555 "fractal.lex"
{
   FractalLexer::getInstance()->advance(yytext);
   FractalLexer::getInstance()->nextLine();
}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 560 "fractal.lex"
{
   /* -- Ignore -- */
   FractalLexer::getInstance()->advance(yytext);
}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 565 "fractal.lex"
{
   FractalLexer::getInstance()->advance(yytext);
   BEGIN INITIAL;
}
	YY_BREAK
/* -- Token handling for STATE_SINGLE_LINE_COMMENT  -- */
case 77:
YY_RULE_SETUP
#line 572 "fractal.lex"
{
   FractalLexer::getInstance()->advance(yytext);
   FractalLexer::getInstance()->nextLine();
   BEGIN INITIAL;
}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 578 "fractal.lex"
{
   /* -- Ignore -- */
   FractalLexer::getInstance()->advance(yytext);
}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 583 "fractal.lex"
ECHO;
	YY_BREAK
#line 1622 "fractal.lex.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(STATE_MULTI_LINE_COMMENT):
case YY_STATE_EOF(STATE_SINGLE_LINE_COMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 309 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 309 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 308);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}
#endif /* YY_NO_INPUT */

#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}



#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 583 "fractal.lex"


int yywrap() { return(1); }

static int my_yyinput(char *buffer, int maxsize)
{
   return(
      FractalLexer::getInstance()->getText(buffer, maxsize)
   );
}
